###

GET http://localhost:4000/api/users

###
GET http://localhost:4000/api/categories

###
GET http://localhost:4000/api/lessons

###
GET http://localhost:4000/api/localizations


###
POST http://localhost:4000/api/lesson

Content-Type: application/json

{
    "name": "testttbgtdfd",
    "content": "testgfdfsf",
    "photo": "photo.jpg",
    "video": "video.mpg",
    "ownerId": 1,
    "categoryId": 1,
    "localizationId": 1,
}


###
DELETE  http://localhost:4000/api/user/1

###
PATCH  http://localhost:4000/api/user/4

Content-Type: application/json

{
   "firstName": "tesgtdjkjkfdf",
    "lastName": "testgfjkldfsf",
    "password": "pafgssworfdsfd",
    "email": "emaifgfdsfl",
    "avatar": "avgfadsftar.jpg" 
}

###
POST http://localhost:4000/api/category

Content-Type: application/json

{
    "name": "new",
    
}

###
POST http://localhost:4000/api/user

Content-Type: application/json

{
  "firstName": "user@user",
  "lastName":  "user@user",
  "password":  "user@user",
  "email":     "user@user",  
  "avatar":    "avatar.jpg",          
}


